# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/jonathan/Desktop/clang/tools/cmake/bin/cmake

# The command to remove a file.
RM = /Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jonathan/Desktop/WebKit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jonathan/Desktop/WebKit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cpack --config ./CPackSourceConfig.cmake /Users/jonathan/Desktop/WebKit/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/jonathan/Desktop/clang/tools/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonathan/Desktop/WebKit/CMakeFiles /Users/jonathan/Desktop/WebKit//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonathan/Desktop/WebKit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bmalloc

# Build rule for target.
bmalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bmalloc
.PHONY : bmalloc

# fast build rule for target.
bmalloc/fast:
	$(MAKE) $(MAKESILENT) -f Source/bmalloc/CMakeFiles/bmalloc.dir/build.make Source/bmalloc/CMakeFiles/bmalloc.dir/build
.PHONY : bmalloc/fast

#=============================================================================
# Target rules for targets named bmalloc_CopyHeaders

# Build rule for target.
bmalloc_CopyHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bmalloc_CopyHeaders
.PHONY : bmalloc_CopyHeaders

# fast build rule for target.
bmalloc_CopyHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/bmalloc/CMakeFiles/bmalloc_CopyHeaders.dir/build.make Source/bmalloc/CMakeFiles/bmalloc_CopyHeaders.dir/build
.PHONY : bmalloc_CopyHeaders/fast

#=============================================================================
# Target rules for targets named WTF

# Build rule for target.
WTF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WTF
.PHONY : WTF

# fast build rule for target.
WTF/fast:
	$(MAKE) $(MAKESILENT) -f Source/WTF/wtf/CMakeFiles/WTF.dir/build.make Source/WTF/wtf/CMakeFiles/WTF.dir/build
.PHONY : WTF/fast

#=============================================================================
# Target rules for targets named WTF_CopyHeaders

# Build rule for target.
WTF_CopyHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WTF_CopyHeaders
.PHONY : WTF_CopyHeaders

# fast build rule for target.
WTF_CopyHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/WTF/wtf/CMakeFiles/WTF_CopyHeaders.dir/build.make Source/WTF/wtf/CMakeFiles/WTF_CopyHeaders.dir/build
.PHONY : WTF_CopyHeaders/fast

#=============================================================================
# Target rules for targets named WTF_CopyPreferences

# Build rule for target.
WTF_CopyPreferences: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WTF_CopyPreferences
.PHONY : WTF_CopyPreferences

# fast build rule for target.
WTF_CopyPreferences/fast:
	$(MAKE) $(MAKESILENT) -f Source/WTF/wtf/CMakeFiles/WTF_CopyPreferences.dir/build.make Source/WTF/wtf/CMakeFiles/WTF_CopyPreferences.dir/build
.PHONY : WTF_CopyPreferences/fast

#=============================================================================
# Target rules for targets named unifdef

# Build rule for target.
unifdef: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unifdef
.PHONY : unifdef

# fast build rule for target.
unifdef/fast:
	$(MAKE) $(MAKESILENT) -f Source/ThirdParty/unifdef/CMakeFiles/unifdef.dir/build.make Source/ThirdParty/unifdef/CMakeFiles/unifdef.dir/build
.PHONY : unifdef/fast

#=============================================================================
# Target rules for targets named Bytecodes

# Build rule for target.
Bytecodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bytecodes
.PHONY : Bytecodes

# fast build rule for target.
Bytecodes/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/Bytecodes.dir/build.make Source/JavaScriptCore/CMakeFiles/Bytecodes.dir/build
.PHONY : Bytecodes/fast

#=============================================================================
# Target rules for targets named JSCBuiltins

# Build rule for target.
JSCBuiltins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JSCBuiltins
.PHONY : JSCBuiltins

# fast build rule for target.
JSCBuiltins/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/JSCBuiltins.dir/build.make Source/JavaScriptCore/CMakeFiles/JSCBuiltins.dir/build
.PHONY : JSCBuiltins/fast

#=============================================================================
# Target rules for targets named LLIntSettingsExtractor

# Build rule for target.
LLIntSettingsExtractor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LLIntSettingsExtractor
.PHONY : LLIntSettingsExtractor

# fast build rule for target.
LLIntSettingsExtractor/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/LLIntSettingsExtractor.dir/build.make Source/JavaScriptCore/CMakeFiles/LLIntSettingsExtractor.dir/build
.PHONY : LLIntSettingsExtractor/fast

#=============================================================================
# Target rules for targets named LLIntOffsetsExtractor

# Build rule for target.
LLIntOffsetsExtractor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LLIntOffsetsExtractor
.PHONY : LLIntOffsetsExtractor

# fast build rule for target.
LLIntOffsetsExtractor/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/build.make Source/JavaScriptCore/CMakeFiles/LLIntOffsetsExtractor.dir/build
.PHONY : LLIntOffsetsExtractor/fast

#=============================================================================
# Target rules for targets named LowLevelInterpreterLib

# Build rule for target.
LowLevelInterpreterLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LowLevelInterpreterLib
.PHONY : LowLevelInterpreterLib

# fast build rule for target.
LowLevelInterpreterLib/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/LowLevelInterpreterLib.dir/build.make Source/JavaScriptCore/CMakeFiles/LowLevelInterpreterLib.dir/build
.PHONY : LowLevelInterpreterLib/fast

#=============================================================================
# Target rules for targets named JavaScriptCore

# Build rule for target.
JavaScriptCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JavaScriptCore
.PHONY : JavaScriptCore

# fast build rule for target.
JavaScriptCore/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/build.make Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/build
.PHONY : JavaScriptCore/fast

#=============================================================================
# Target rules for targets named JavaScriptCore_CopyHeaders

# Build rule for target.
JavaScriptCore_CopyHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JavaScriptCore_CopyHeaders
.PHONY : JavaScriptCore_CopyHeaders

# fast build rule for target.
JavaScriptCore_CopyHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/JavaScriptCore_CopyHeaders.dir/build.make Source/JavaScriptCore/CMakeFiles/JavaScriptCore_CopyHeaders.dir/build
.PHONY : JavaScriptCore_CopyHeaders/fast

#=============================================================================
# Target rules for targets named JavaScriptCore_CopyPrivateHeaders

# Build rule for target.
JavaScriptCore_CopyPrivateHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JavaScriptCore_CopyPrivateHeaders
.PHONY : JavaScriptCore_CopyPrivateHeaders

# fast build rule for target.
JavaScriptCore_CopyPrivateHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/JavaScriptCore_CopyPrivateHeaders.dir/build.make Source/JavaScriptCore/CMakeFiles/JavaScriptCore_CopyPrivateHeaders.dir/build
.PHONY : JavaScriptCore_CopyPrivateHeaders/fast

#=============================================================================
# Target rules for targets named JavaScriptCoreSharedScripts

# Build rule for target.
JavaScriptCoreSharedScripts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JavaScriptCoreSharedScripts
.PHONY : JavaScriptCoreSharedScripts

# fast build rule for target.
JavaScriptCoreSharedScripts/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/CMakeFiles/JavaScriptCoreSharedScripts.dir/build.make Source/JavaScriptCore/CMakeFiles/JavaScriptCoreSharedScripts.dir/build
.PHONY : JavaScriptCoreSharedScripts/fast

#=============================================================================
# Target rules for targets named jsc

# Build rule for target.
jsc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jsc
.PHONY : jsc

# fast build rule for target.
jsc/fast:
	$(MAKE) $(MAKESILENT) -f Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/build.make Source/JavaScriptCore/shell/CMakeFiles/jsc.dir/build
.PHONY : jsc/fast

#=============================================================================
# Target rules for targets named WebInspectorUI

# Build rule for target.
WebInspectorUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebInspectorUI
.PHONY : WebInspectorUI

# fast build rule for target.
WebInspectorUI/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebInspectorUI/CMakeFiles/WebInspectorUI.dir/build.make Source/WebInspectorUI/CMakeFiles/WebInspectorUI.dir/build
.PHONY : WebInspectorUI/fast

#=============================================================================
# Target rules for targets named WebCore

# Build rule for target.
WebCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebCore
.PHONY : WebCore

# fast build rule for target.
WebCore/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/CMakeFiles/WebCore.dir/build.make Source/WebCore/CMakeFiles/WebCore.dir/build
.PHONY : WebCore/fast

#=============================================================================
# Target rules for targets named WebCoreTestSupport

# Build rule for target.
WebCoreTestSupport: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebCoreTestSupport
.PHONY : WebCoreTestSupport

# fast build rule for target.
WebCoreTestSupport/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/build.make Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/build
.PHONY : WebCoreTestSupport/fast

#=============================================================================
# Target rules for targets named WebCoreBindings

# Build rule for target.
WebCoreBindings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebCoreBindings
.PHONY : WebCoreBindings

# fast build rule for target.
WebCoreBindings/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/CMakeFiles/WebCoreBindings.dir/build.make Source/WebCore/CMakeFiles/WebCoreBindings.dir/build
.PHONY : WebCoreBindings/fast

#=============================================================================
# Target rules for targets named WebCoreTestSupportBindings

# Build rule for target.
WebCoreTestSupportBindings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebCoreTestSupportBindings
.PHONY : WebCoreTestSupportBindings

# fast build rule for target.
WebCoreTestSupportBindings/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/CMakeFiles/WebCoreTestSupportBindings.dir/build.make Source/WebCore/CMakeFiles/WebCoreTestSupportBindings.dir/build
.PHONY : WebCoreTestSupportBindings/fast

#=============================================================================
# Target rules for targets named WebCore_CopyPrivateHeaders

# Build rule for target.
WebCore_CopyPrivateHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebCore_CopyPrivateHeaders
.PHONY : WebCore_CopyPrivateHeaders

# fast build rule for target.
WebCore_CopyPrivateHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/CMakeFiles/WebCore_CopyPrivateHeaders.dir/build.make Source/WebCore/CMakeFiles/WebCore_CopyPrivateHeaders.dir/build
.PHONY : WebCore_CopyPrivateHeaders/fast

#=============================================================================
# Target rules for targets named Copy_WebCoreTestSupportPrivateHeaders

# Build rule for target.
Copy_WebCoreTestSupportPrivateHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Copy_WebCoreTestSupportPrivateHeaders
.PHONY : Copy_WebCoreTestSupportPrivateHeaders

# fast build rule for target.
Copy_WebCoreTestSupportPrivateHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/CMakeFiles/Copy_WebCoreTestSupportPrivateHeaders.dir/build.make Source/WebCore/CMakeFiles/Copy_WebCoreTestSupportPrivateHeaders.dir/build
.PHONY : Copy_WebCoreTestSupportPrivateHeaders/fast

#=============================================================================
# Target rules for targets named PAL

# Build rule for target.
PAL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PAL
.PHONY : PAL

# fast build rule for target.
PAL/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/PAL/pal/CMakeFiles/PAL.dir/build.make Source/WebCore/PAL/pal/CMakeFiles/PAL.dir/build
.PHONY : PAL/fast

#=============================================================================
# Target rules for targets named PAL_CopyHeaders

# Build rule for target.
PAL_CopyHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PAL_CopyHeaders
.PHONY : PAL_CopyHeaders

# fast build rule for target.
PAL_CopyHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebCore/PAL/pal/CMakeFiles/PAL_CopyHeaders.dir/build.make Source/WebCore/PAL/pal/CMakeFiles/PAL_CopyHeaders.dir/build
.PHONY : PAL_CopyHeaders/fast

#=============================================================================
# Target rules for targets named WebKitLegacy

# Build rule for target.
WebKitLegacy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebKitLegacy
.PHONY : WebKitLegacy

# fast build rule for target.
WebKitLegacy/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKitLegacy/CMakeFiles/WebKitLegacy.dir/build.make Source/WebKitLegacy/CMakeFiles/WebKitLegacy.dir/build
.PHONY : WebKitLegacy/fast

#=============================================================================
# Target rules for targets named WebKitLegacy_CopyHeaders

# Build rule for target.
WebKitLegacy_CopyHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebKitLegacy_CopyHeaders
.PHONY : WebKitLegacy_CopyHeaders

# fast build rule for target.
WebKitLegacy_CopyHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKitLegacy/CMakeFiles/WebKitLegacy_CopyHeaders.dir/build.make Source/WebKitLegacy/CMakeFiles/WebKitLegacy_CopyHeaders.dir/build
.PHONY : WebKitLegacy_CopyHeaders/fast

#=============================================================================
# Target rules for targets named WebProcess

# Build rule for target.
WebProcess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebProcess
.PHONY : WebProcess

# fast build rule for target.
WebProcess/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKit/CMakeFiles/WebProcess.dir/build.make Source/WebKit/CMakeFiles/WebProcess.dir/build
.PHONY : WebProcess/fast

#=============================================================================
# Target rules for targets named NetworkProcess

# Build rule for target.
NetworkProcess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NetworkProcess
.PHONY : NetworkProcess

# fast build rule for target.
NetworkProcess/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKit/CMakeFiles/NetworkProcess.dir/build.make Source/WebKit/CMakeFiles/NetworkProcess.dir/build
.PHONY : NetworkProcess/fast

#=============================================================================
# Target rules for targets named WebKit

# Build rule for target.
WebKit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebKit
.PHONY : WebKit

# fast build rule for target.
WebKit/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKit/CMakeFiles/WebKit.dir/build.make Source/WebKit/CMakeFiles/WebKit.dir/build
.PHONY : WebKit/fast

#=============================================================================
# Target rules for targets named WebKit_CopyHeaders

# Build rule for target.
WebKit_CopyHeaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebKit_CopyHeaders
.PHONY : WebKit_CopyHeaders

# fast build rule for target.
WebKit_CopyHeaders/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKit/CMakeFiles/WebKit_CopyHeaders.dir/build.make Source/WebKit/CMakeFiles/WebKit_CopyHeaders.dir/build
.PHONY : WebKit_CopyHeaders/fast

#=============================================================================
# Target rules for targets named WebKitSandboxProfiles

# Build rule for target.
WebKitSandboxProfiles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebKitSandboxProfiles
.PHONY : WebKitSandboxProfiles

# fast build rule for target.
WebKitSandboxProfiles/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKit/CMakeFiles/WebKitSandboxProfiles.dir/build.make Source/WebKit/CMakeFiles/WebKitSandboxProfiles.dir/build
.PHONY : WebKitSandboxProfiles/fast

#=============================================================================
# Target rules for targets named WebContentProcessNib

# Build rule for target.
WebContentProcessNib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebContentProcessNib
.PHONY : WebContentProcessNib

# fast build rule for target.
WebContentProcessNib/fast:
	$(MAKE) $(MAKESILENT) -f Source/WebKit/CMakeFiles/WebContentProcessNib.dir/build.make Source/WebKit/CMakeFiles/WebContentProcessNib.dir/build
.PHONY : WebContentProcessNib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Bytecodes"
	@echo "... Copy_WebCoreTestSupportPrivateHeaders"
	@echo "... JSCBuiltins"
	@echo "... JavaScriptCoreSharedScripts"
	@echo "... JavaScriptCore_CopyHeaders"
	@echo "... JavaScriptCore_CopyPrivateHeaders"
	@echo "... PAL_CopyHeaders"
	@echo "... WTF_CopyHeaders"
	@echo "... WTF_CopyPreferences"
	@echo "... WebContentProcessNib"
	@echo "... WebCoreBindings"
	@echo "... WebCoreTestSupportBindings"
	@echo "... WebCore_CopyPrivateHeaders"
	@echo "... WebInspectorUI"
	@echo "... WebKitLegacy_CopyHeaders"
	@echo "... WebKitSandboxProfiles"
	@echo "... WebKit_CopyHeaders"
	@echo "... bmalloc_CopyHeaders"
	@echo "... JavaScriptCore"
	@echo "... LLIntOffsetsExtractor"
	@echo "... LLIntSettingsExtractor"
	@echo "... LowLevelInterpreterLib"
	@echo "... NetworkProcess"
	@echo "... PAL"
	@echo "... WTF"
	@echo "... WebCore"
	@echo "... WebCoreTestSupport"
	@echo "... WebKit"
	@echo "... WebKitLegacy"
	@echo "... WebProcess"
	@echo "... bmalloc"
	@echo "... jsc"
	@echo "... unifdef"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

