// The font families a stock macOS Tahoe 26 installation makes available to web content, and a stand-in
// on this system for each Tahoe family with Latin letters that 10.9 does not ship.
//
// The families are those of the faces Apple lists in "Fonts included with macOS Tahoe"
// (support.apple.com/122869), in both its installed and its document-support sections, less the
// faces the com.apple.MobileAsset.Font8 catalog delivers to macOS only on download
// (PlatformDelivery macOS-download or macOS-autoactivated). A Tahoe family whose faces carry no Latin
// letters -- the Noto Sans and Noto Serif script families -- gets no stand-in: a page measuring Latin
// text sees the fallback font there as it does here.
#include "wk_font_catalog.h"

#include <stdlib.h>
#include <strings.h>

static const char *const wk_tahoeFamilies[] = {
    "Academy Engraved LET",
    "Al Bayan",
    "Al Nile",
    "Al Tarikh",
    "American Typewriter",
    "Andale Mono",
    "Apple Braille",
    "Apple Chancery",
    "Apple Color Emoji",
    "Apple SD Gothic Neo",
    "Apple Symbols",
    "AppleGothic",
    "AppleMyungjo",
    "Arial",
    "Arial Black",
    "Arial Hebrew",
    "Arial Hebrew Scholar",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Asphalt",
    "Athelas",
    "Avenir",
    "Avenir Next",
    "Avenir Next Condensed",
    "Ayuthaya",
    "Baghdad",
    "Balega",
    "Bangla MN",
    "Bangla Sangam MN",
    "Baskerville",
    "Bebas Neue",
    "Beirut",
    "Big Caslon",
    "Blackmoor LET",
    "Bodoni 72",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "Bodoni Ornaments",
    "Bradley Hand",
    "Brush Script MT",
    "Carlito",
    "Chalkboard",
    "Chalkboard SE",
    "Chalkduster",
    "Charter",
    "Cochin",
    "Comic Sans MS",
    "Copperplate",
    "Corsiva Hebrew",
    "Courier",
    "Courier New",
    "Damascus",
    "Dear Joe Four",
    "DecoType Naskh",
    "Devanagari MT",
    "Devanagari Sangam MN",
    "Didot",
    "DIN Alternate",
    "DIN Condensed",
    "Diwan Kufi",
    "Diwan Thuluth",
    "Druk",
    "Druk Text",
    "Druk Wide",
    "Euphemia UCAS",
    "Fakt Slab Stencil Pro",
    "Farah",
    "Farisi",
    "Futura",
    "Galvji",
    "GB18030 Bitmap",
    "Geeza Pro",
    "Geneva",
    "Georgia",
    "Gill Sans",
    "Grantha Sangam MN",
    "Gujarati MT",
    "Gujarati Sangam MN",
    "GungSeo",
    "Gurmukhi MN",
    "Gurmukhi MT",
    "Gurmukhi Sangam MN",
    "Heiti SC",
    "Heiti TC",
    "Helvetica",
    "Helvetica Neue",
    "Herculanum",
    "Hiragino Kaku Gothic Pro",
    "Hiragino Kaku Gothic ProN",
    "Hiragino Kaku Gothic Std",
    "Hiragino Kaku Gothic StdN",
    "Hiragino Maru Gothic Pro",
    "Hiragino Maru Gothic ProN",
    "Hiragino Mincho Pro",
    "Hiragino Mincho ProN",
    "Hiragino Sans",
    "Hiragino Sans GB",
    "Hoefler Text",
    "Impact",
    "InaiMathi",
    "Iowan Old Style",
    "ITF Devanagari",
    "ITF Devanagari Marathi",
    "Jazz LET",
    "Journal Sans New",
    "Kailasa",
    "Kannada MN",
    "Kannada Sangam MN",
    "Kefa",
    "Khmer MN",
    "Khmer Sangam MN",
    "Kohinoor Bangla",
    "Kohinoor Devanagari",
    "Kohinoor Gujarati",
    "Kohinoor Telugu",
    "Kokonor",
    "Krungthep",
    "KufiStandardGK",
    "Lao MN",
    "Lao Sangam MN",
    "LiHei Pro",
    "Lucida Grande",
    "Luminari",
    "Malayalam MN",
    "Malayalam Sangam MN",
    "Marion",
    "Marker Felt",
    "Menlo",
    "Microsoft Sans Serif",
    "Mishafi",
    "Mishafi Gold",
    "Monaco",
    "Mshtakan",
    "MuktaMahee",
    "MuktaMahee ExtraBold",
    "MuktaMahee ExtraLight",
    "MuktaMahee Medium",
    "MuktaMahee SemiBold",
    "Muna",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "Nadeem",
    "New Peninim MT",
    "Noteworthy",
    "Noto Nastaliq Urdu",
    "Noto Sans Adlam",
    "Noto Sans Armenian",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Bassa Vah",
    "Noto Sans Batak",
    "Noto Sans Bhaiksuki",
    "Noto Sans Brahmi",
    "Noto Sans Buginese",
    "Noto Sans Buhid",
    "Noto Sans Canadian Aboriginal",
    "Noto Sans Carian",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Chakma",
    "Noto Sans Cham",
    "Noto Sans Coptic",
    "Noto Sans Cuneiform",
    "Noto Sans Cypriot",
    "Noto Sans Duployan",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Elbasan",
    "Noto Sans Glagolitic",
    "Noto Sans Gothic",
    "Noto Sans Gunjala Gondi",
    "Noto Sans Hanifi Rohingya",
    "Noto Sans Hanunoo",
    "Noto Sans Hatran",
    "Noto Sans Imperial Aramaic",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Javanese",
    "Noto Sans Kaithi",
    "Noto Sans Kannada",
    "Noto Sans Kayah Li",
    "Noto Sans Kharoshthi",
    "Noto Sans Khojki",
    "Noto Sans Khudawadi",
    "Noto Sans Lepcha",
    "Noto Sans Limbu",
    "Noto Sans Linear A",
    "Noto Sans Linear B",
    "Noto Sans Lisu",
    "Noto Sans Lycian",
    "Noto Sans Lydian",
    "Noto Sans Mahajani",
    "Noto Sans Mandaic",
    "Noto Sans Manichaean",
    "Noto Sans Marchen",
    "Noto Sans Masaram Gondi",
    "Noto Sans Meetei Mayek",
    "Noto Sans Mende Kikakui",
    "Noto Sans Meroitic",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans Mongolian",
    "Noto Sans Mro",
    "Noto Sans Multani",
    "Noto Sans Myanmar",
    "Noto Sans Nabataean",
    "Noto Sans Nag Mundari",
    "Noto Sans New Tai Lue",
    "Noto Sans Newa",
    "Noto Sans NKo",
    "Noto Sans Ol Chiki",
    "Noto Sans Old Hungarian",
    "Noto Sans Old Italic",
    "Noto Sans Old North Arabian",
    "Noto Sans Old Permic",
    "Noto Sans Old Persian",
    "Noto Sans Old South Arabian",
    "Noto Sans Old Turkic",
    "Noto Sans Oriya",
    "Noto Sans Osage",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Palmyrene",
    "Noto Sans Pau Cin Hau",
    "Noto Sans PhagsPa",
    "Noto Sans Phoenician",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Rejang",
    "Noto Sans Samaritan",
    "Noto Sans Saurashtra",
    "Noto Sans Sharada",
    "Noto Sans Siddham",
    "Noto Sans Sora Sompeng",
    "Noto Sans Sundanese",
    "Noto Sans Syloti Nagri",
    "Noto Sans Syriac",
    "Noto Sans Tagalog",
    "Noto Sans Tagbanwa",
    "Noto Sans Tai Le",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet",
    "Noto Sans Takri",
    "Noto Sans Thaana",
    "Noto Sans Tifinagh",
    "Noto Sans Tirhuta",
    "Noto Sans Ugaritic",
    "Noto Sans Vai",
    "Noto Sans Wancho",
    "Noto Sans Warang Citi",
    "Noto Sans Yi",
    "Noto Sans Zawgyi",
    "Noto Serif Ahom",
    "Noto Serif Balinese",
    "Noto Serif Hmong Nyiakeng",
    "Noto Serif Myanmar",
    "Noto Serif Yezidi",
    "Optima",
    "Oriya MN",
    "Oriya Sangam MN",
    "Palatino",
    "Papyrus",
    "Party LET",
    "Phosphate",
    "Plantagenet Cherokee",
    "PT Mono",
    "PT Sans",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Serif",
    "PT Serif Caption",
    "Raanana",
    "Rockwell",
    "Sana",
    "Santa Fe LET",
    "Sathu",
    "Savoye LET",
    "Scheme",
    "Seravek",
    "Shree Devanagari 714",
    "SignPainter-HouseScript",
    "Silom",
    "Sinhala MN",
    "Sinhala Sangam MN",
    "Snell Roundhand",
    "Songti SC",
    "Songti TC",
    "STIX Two Math",
    "STIX Two Text",
    "STIXGeneral",
    "STIXIntegralsD",
    "STIXIntegralsSm",
    "STIXIntegralsUp",
    "STIXIntegralsUpD",
    "STIXIntegralsUpSm",
    "STIXNonUnicode",
    "STIXSizeFiveSym",
    "STIXSizeFourSym",
    "STIXSizeOneSym",
    "STIXSizeThreeSym",
    "STIXSizeTwoSym",
    "STIXVariants",
    "STSong",
    "Sukhumvit Set",
    "Superclarendon",
    "Symbol",
    "Tahoma",
    "Tamil MN",
    "Tamil Sangam MN",
    "Telugu MN",
    "Telugu Sangam MN",
    "The Hand Serif",
    "Thonburi",
    "Times",
    "Times New Roman",
    "Trattatello",
    "Trebuchet MS",
    "Type Embellishments One LET",
    "Verdana",
    "Waseem",
    "Webdings",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Zapf Dingbats",
    "Zapfino",
};

static const struct { const char *family; const char *standIn; } wk_standIns[] = {
    { "Academy Engraved LET", "Copperplate" },
    { "Arial Hebrew Scholar", "Arial Hebrew" },
    { "Asphalt", "Impact" },
    { "Balega", "Impact" },
    { "Bebas Neue", "DIN Condensed" },
    { "Blackmoor LET", "Herculanum" },
    { "Bodoni 72", "Didot" },
    { "Bodoni 72 Oldstyle", "Didot" },
    { "Bodoni 72 Smallcaps", "Didot" },
    { "Bodoni Ornaments", "Zapf Dingbats" },
    { "Bradley Hand", "Noteworthy" },
    { "Carlito", "Seravek" },
    { "Dear Joe Four", "Chalkboard" },
    { "Druk", "Impact" },
    { "Druk Text", "Impact" },
    { "Druk Wide", "Impact" },
    { "Fakt Slab Stencil Pro", "Superclarendon" },
    { "Galvji", "Helvetica Neue" },
    { "Grantha Sangam MN", "Tamil Sangam MN" },
    { "Hiragino Sans", "Hiragino Kaku Gothic ProN" },
    { "ITF Devanagari", "Devanagari Sangam MN" },
    { "ITF Devanagari Marathi", "Devanagari Sangam MN" },
    { "Jazz LET", "Marker Felt" },
    { "Journal Sans New", "Futura" },
    { "Kohinoor Bangla", "Bangla Sangam MN" },
    { "Kohinoor Devanagari", "Devanagari Sangam MN" },
    { "Kohinoor Gujarati", "Gujarati Sangam MN" },
    { "Kohinoor Telugu", "Telugu Sangam MN" },
    { "Luminari", "Herculanum" },
    { "Mishafi Gold", "Mishafi" },
    { "MuktaMahee", "Gurmukhi Sangam MN" },
    { "MuktaMahee ExtraBold", "Gurmukhi Sangam MN" },
    { "MuktaMahee ExtraLight", "Gurmukhi Sangam MN" },
    { "MuktaMahee Medium", "Gurmukhi Sangam MN" },
    { "MuktaMahee SemiBold", "Gurmukhi Sangam MN" },
    { "Party LET", "Brush Script MT" },
    { "Phosphate", "Impact" },
    { "Rockwell", "Superclarendon" },
    { "Santa Fe LET", "Snell Roundhand" },
    { "Scheme", "Futura" },
    { "Shree Devanagari 714", "Devanagari Sangam MN" },
    { "SignPainter-HouseScript", "Brush Script MT" },
    { "STIX Two Math", "STIXGeneral" },
    { "STIX Two Text", "STIXGeneral" },
    { "Sukhumvit Set", "Thonburi" },
    { "The Hand Serif", "Noteworthy" },
    { "Trattatello", "Apple Chancery" },
    { "Type Embellishments One LET", "Zapf Dingbats" },
};

static int wk_compareFamily(const void *key, const void *element)
{
    return strcasecmp((const char *)key, *(const char *const *)element);
}

static int wk_compareStandIn(const void *key, const void *element)
{
    return strcasecmp((const char *)key, *(const char *const *)element);
}

bool wk_font_family_ships_with_tahoe(const char *family)
{
    return family && bsearch(family, wk_tahoeFamilies, sizeof(wk_tahoeFamilies) / sizeof(wk_tahoeFamilies[0]),
        sizeof(wk_tahoeFamilies[0]), wk_compareFamily);
}

const char *wk_font_family_stand_in(const char *family)
{
    if (!family)
        return NULL;
    const char *const *entry = bsearch(family, wk_standIns, sizeof(wk_standIns) / sizeof(wk_standIns[0]),
        sizeof(wk_standIns[0]), wk_compareStandIn);
    return entry ? entry[1] : NULL;
}
