#!/bin/bash
# Build and run the Cocoa curl transport tests against WebKitBuild/Release, with every fixture they need.
#
#   MavericksSupport/tests/cocoa-curl/run.sh [--no-build] [test-name ...]     (default: every test)
#
# Fixtures, all loopback-only, started here and stopped on exit:
#   18981 cocoa-curl-probe-server.py          HTTP framing cases, /echo, and the /page ledger
#   18982 cocoa-curl-download-server.py       downloads, ranges, handoff
#   18983 cocoa-curl-download-server.py       private WK2 resume
#   18984 cocoa-curl-auth-server.py           origin Basic/Digest/NTLM
#   18985 cocoa-curl-auth-server.py --proxy   proxy authentication and routing
#   18987 cocoa-curl-compressed-server.py     identity/gzip/deflate/br bodies (brotli encoder built from deps)
#   18988 cocoa-curl-header-delivery-server.py  header sections carrying a line that is not a field line
#   18989 cocoa-curl-header-delivery-server.py --proxy  CONNECT proxy whose tunnel response carries one
#   19445 cocoa-curl-tls-fixtures.py serve    HTTPS on a leaf signed by the run's own root, trusted below
#   19446 cocoa-curl-tls-fixtures.py serve    untrusted self-signed HTTPS
#   19447 cocoa-curl-tls-fixtures.py serve    client certificate required, TLS 1.2
#   19448 cocoa-curl-tls-fixtures.py serve    client certificate required, TLS 1.3
#   19449 cocoa-curl-tls-fixtures.py framing  close-delimited and truncated framings, closed with no close_notify
#   19450 cocoa-curl-tls-fixtures.py framing  the same close over HTTP/2
#   19451 cocoa-curl-tls-fixtures.py serve    trusted chain, TLS 1.1 only
# The certificate tests read identity.p12, ec-identity.p12 and server.der from /private/tmp/curl-identity-test,
# regenerated by cocoa-curl-tls-fixtures.py make on every run. That run's root is trusted in the system
# keychain for the length of the run so one fixture presents a chain the platform accepts, and removed again
# on exit; the suite reaches nothing outside loopback. Per-test output lands in
# WebKitBuild/Release/cocoa-curl-tests/fixtures/<test>.log; the summary and exit status report the failures.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"
BUILD="$ROOT/WebKitBuild/Release"
OUT="$BUILD/cocoa-curl-tests"
FX="$OUT/fixtures"
DEPS="$ROOT/MavericksSupport/deps/build"
POLY="$ROOT/MavericksSupport/polyfill/build"
TC="$ROOT/MavericksSupport/toolchain/build/clang/bin"
LOG=/tmp/wk_build.log
IDENTITIES=/private/tmp/curl-identity-test
# The trusted root lives at its own stable path, outside the directory `make` rewrites, so a run killed
# before its cleanup still leaves the next run a handle to remove that exact certificate.
TRUSTED_ROOT=/private/tmp/curl-identity-test-root.pem
# The common-name prefix cocoa-curl-tls-fixtures.py gives that root, which is how a killed run's copy is
# found and removed.
ROOT_NAME="WK Cocoa curl test root"
PY=python3
BUILD_TESTS=1
[ "${1:-}" = "--no-build" ] && { BUILD_TESTS=0; shift; }
TESTS=("$@"); [ ${#TESTS[@]} -gt 0 ] || TESTS=($(cd "$HERE" && ls *.mm *.c | sed 's/\.mm$//; s/\.c$//'))
# One run at a time: the fixtures own fixed ports, $FX is wiped below, and the run's own root is
# trusted machine-wide for its length, so a second invocation would destroy the first's state and
# report against it. The lock is a directory (bash 3.2 has no flock) holding the owner's pid, and is
# stale once that pid is gone; ps answers that for a root-owned run started under sudo as well as for
# our own, which kill -0 cannot.
LOCK="$OUT/.cocoa-curl.lock"
mkdir -p "$OUT"
if ! mkdir "$LOCK" 2>/dev/null; then
    owner=$(cat "$LOCK/pid" 2>/dev/null)
    if [ -n "$owner" ] && ps -p "$owner" >/dev/null 2>&1; then
        echo "cocoa-curl tests: LOCKED, another run.sh (pid $owner) is in progress"
        exit 3
    fi
    rm -rf "$LOCK" 2>/dev/null
    mkdir "$LOCK" 2>/dev/null || { echo "cocoa-curl tests: LOCKED, stale lock at $LOCK cannot be removed"; exit 3; }
fi
echo $$ > "$LOCK/pid"
trap 'rm -rf "$LOCK"' EXIT INT TERM
rm -rf "$FX"; mkdir -p "$FX/keychains"
rm -rf /private/tmp/curl-legacy-download-tests; mkdir -p /private/tmp/curl-legacy-download-tests

if [ $BUILD_TESTS = 1 ]; then
    # A build failure reports in the shape the run below reports in, so whatever watches this suite
    # sees a result line either way, and exits 2 so a caller can tell it from tests that ran and failed.
    exec 3>&1
    build_output=$("$HERE/build.sh" "${TESTS[@]}" | tee /dev/fd/3)
    build_status=$?
    exec 3>&-
    if [ $build_status != 0 ]; then
        broken=$(printf '%s\n' "$build_output" | sed -n 's/^  FAILED \([^ ]*\) (see .*/\1/p')
        printf "cocoa-curl tests: BUILD FAILED, %s did not compile\n" "$(printf '%s' "$broken" | grep -c .)"
        [ -n "$broken" ] && printf "  FAILED %s (see $LOG)\n" $broken
        exit 2
    fi
fi
# A framework build leaves the tree's own Mach-Os homed the way the 26.1 SDK linked them, which dyld
# on 10.9 refuses; the tests load that tree, so every run prepares it, built here or not.
bash "$ROOT/MavericksSupport/scripts/make-build-binaries-runnable.sh" >> "$LOG" 2>&1 \
    || { echo "cocoa-curl: could not make the build tree loadable (see $LOG)"; exit 1; }
if [ ! -f "$OUT/libbrotlienc.dylib" ]; then
    echo "### cocoa-curl brotli encoder dylib" >> "$LOG"
    "$TC/clang" -dynamiclib -mmacosx-version-min=10.9 -Wl,-force_load,"$DEPS/lib/libbrotlienc.a" -Wl,-force_load,"$DEPS/lib/libbrotlicommon.a" \
        "$POLY/libpolyfill.a" -install_name "$OUT/libbrotlienc.dylib" -o "$OUT/libbrotlienc.dylib" >> "$LOG" 2>&1 || { echo "cocoa-curl: brotli encoder build failed (see $LOG)"; exit 1; }
fi
untrust_root() {
    [ -f "$TRUSTED_ROOT" ] && sudo -n security remove-trusted-cert -d "$TRUSTED_ROOT" 2>/dev/null
    rm -f "$TRUSTED_ROOT"
    # remove-trusted-cert drops the trust setting and leaves the certificate itself in the keychain.
    # Each is deleted under its own full name, which a timestamp makes unique, so a backlog of them
    # clears in one pass and no name is ever matched as a prefix of another certificate's.
    security find-certificate -a -c "$ROOT_NAME" /Library/Keychains/System.keychain 2>/dev/null \
        | sed -n 's/^ *"alis"<blob>="\(.*\)"$/\1/p' | sort -u | while read -r name; do
            sudo -n security delete-certificate -c "$name" /Library/Keychains/System.keychain >/dev/null 2>&1
        done
    return 0
}
untrust_root
$PY "$HERE/cocoa-curl-tls-fixtures.py" make "$IDENTITIES" > "$FX/tls-fixtures.log" 2>&1 || { echo "cocoa-curl: identity fixtures failed"; cat "$FX/tls-fixtures.log"; exit 1; }

cp "$IDENTITIES/root.pem" "$TRUSTED_ROOT"
if ! sudo -n security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$TRUSTED_ROOT" >> "$FX/tls-fixtures.log" 2>&1; then
    echo "cocoa-curl: could not trust the run's test root (see $FX/tls-fixtures.log)"; rm -f "$TRUSTED_ROOT"; exit 1
fi
PIDS=()
fixture() { local name=$1; shift; "$@" > "$FX/$name.log" 2>&1 & PIDS+=($!); }
cleanup() {
    for p in "${PIDS[@]:-}"; do [ -n "$p" ] && kill "$p" 2>/dev/null; done
    untrust_root
    rm -rf "$LOCK"
    return 0
}
trap cleanup EXIT INT TERM
fixture probe      $PY "$HERE/cocoa-curl-probe-server.py" --port 18981 --log-dir "$FX/probe"
fixture download   $PY "$HERE/cocoa-curl-download-server.py" --port 18982 --log "$FX/download-18982.jsonl"
fixture resume     $PY "$HERE/cocoa-curl-download-server.py" --port 18983 --log "$FX/download-18983.jsonl"
fixture auth       $PY "$HERE/cocoa-curl-auth-server.py"
fixture auth-proxy $PY "$HERE/cocoa-curl-auth-server.py" --proxy
fixture compressed $PY "$HERE/cocoa-curl-compressed-server.py" --port 18987 --brotli-library "$OUT/libbrotlienc.dylib"
fixture header-delivery       $PY "$HERE/cocoa-curl-header-delivery-server.py" --port 18988
fixture header-delivery-proxy $PY "$HERE/cocoa-curl-header-delivery-server.py" --port 18989 --proxy
fixture tls-trusted   $PY "$HERE/cocoa-curl-tls-fixtures.py" serve "$IDENTITIES" --port 19445 --chain trusted
fixture tls-untrusted $PY "$HERE/cocoa-curl-tls-fixtures.py" serve "$IDENTITIES" --port 19446
fixture tls-mtls-12   $PY "$HERE/cocoa-curl-tls-fixtures.py" serve "$IDENTITIES" --port 19447 --client-auth --tls 1.2
fixture tls-mtls-13   $PY "$HERE/cocoa-curl-tls-fixtures.py" serve "$IDENTITIES" --port 19448 --client-auth --tls 1.3
fixture tls-framing   $PY "$HERE/cocoa-curl-tls-fixtures.py" framing "$IDENTITIES" --port 19449
fixture tls-framing-h2 $PY "$HERE/cocoa-curl-tls-fixtures.py" framing "$IDENTITIES" --port 19450 --h2
fixture tls-11        $PY "$HERE/cocoa-curl-tls-fixtures.py" serve "$IDENTITIES" --port 19451 --chain trusted --tls 1.1
for port in 18981 18982 18983 18984 18985 18987 18988 18989 19445 19446 19447 19448 19449 19450 19451; do
    for i in 1 2 3 4 5 6 7 8 9 10; do nc -z 127.0.0.1 $port 2>/dev/null && break; sleep 0.5; done
    nc -z 127.0.0.1 $port 2>/dev/null || { echo "cocoa-curl: fixture on $port did not start"; grep -l "" "$FX"/*.log | xargs tail -n 3; exit 1; }
done

# Arguments each program takes; the rest take none.
args_for() {
    case "$1" in
        cocoa-curl-legacy-ledger) echo "http://127.0.0.1:18981/page?browser=legacy&run=1 $FX/legacy-ledger.json";;
        cocoa-curl-network-identity-refused) echo "$FX/keychains";;
        curl-http2-stream-completion) echo "$IDENTITIES/server.pem $IDENTITIES/server.key";;
        native-socket-readiness) echo "socket";;
    esac
}
failed=0; passed=0; summary=""
run_one() {
    local t=$1; shift
    local label=$t; [ $# -gt 0 ] && label="$t $*"
    # Quartz's installed-framework dependencies share the test's build-tree framework images.
    DYLD_FRAMEWORK_PATH="$BUILD/lib${DYLD_FRAMEWORK_PATH:+:$DYLD_FRAMEWORK_PATH}" \
        __XPC_DYLD_FRAMEWORK_PATH="$BUILD/lib${DYLD_FRAMEWORK_PATH:+:$DYLD_FRAMEWORK_PATH}" \
        perl -e 'alarm shift; exec @ARGV' 180 "$OUT/$t" "$@" > "$FX/$t.log" 2>&1
    local rc=$?
    local last; last=$(grep -v "^objc\[" "$FX/$t.log" | tail -n 1)
    if [ $rc = 0 ]; then passed=$((passed+1)); summary="$summary  PASS $label -- $last\n"
    else failed=$((failed+1)); summary="$summary  FAIL $label (rc=$rc) -- $last\n"; fi
}
for t in "${TESTS[@]}"; do
    [ -x "$OUT/$t" ] || { failed=$((failed+1)); summary="$summary  FAIL $t (not built)\n"; continue; }
    run_one "$t" $(args_for "$t")
    [ "$t" = native-socket-readiness ] && run_one "$t" descriptor
done
printf "cocoa-curl tests: passed=%d failed=%d\n%b" "$passed" "$failed" "$summary"
[ $failed = 0 ]
